version: '3.9'

services:
  web:
    build: .
    container_name: django_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - DATABASE_URL=sqlite:///db.sqlite3

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: googleform_db
      POSTGRES_USER: googleform_user
      POSTGRES_PASSWORD: googleform_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
